### PR TITLE
Add secure erase for SSDs

### PR DESCRIPTION
**Pull request by abulhol**
See: https://github.com/FOGProject/fos/issues/40
I haven't been able to test it yet, because I don't have a machine with an SSD at hand, but will so so soon. 
If you have the chance, try it out.

### CODE REVIEW

**Comment by wayneworkman** [comment]
We definitely need to test this code before merging. Also need to validate this actually is a secure wipe in all cases where it would be selected.

**Comment by abulhol** [comment]
@wayneworkman I will let you know what my tests say - do you have the time and setup where you can test this anytime soon?
As you saw in the commit, I don't differentiate between "fast", "normal" and "full" wipe for secure erase, as it does not make sense. So the info in the web UI would need to be updated as well then.
What do you mean by 
> Also need to validate this actually is a secure wipe in all cases where it would be selected
?

**Comment by abulhol** [comment]
Testing shows that the updated `fog.wipe` does not break anything, but secure erase does not work at least on Intel NUCs, because the disk is "frozen". See more information in my Github issue https://github.com/FOGProject/fos/issues/40

**Comment by Sebastian-Roth** [comment]
@abulhol @mastacontrola I am wondering if we should still merge this into the official code.

**Comment by mastacontrola** [comment]
I’m assuming the “fallback” is to use shred/dd if the drive is frozen and/or doesn’t support secure erase?

If that’s the case I don’t see why we shouldn’t merge this in.

If an ssd does support and is not frozen, why do a drive intensive operation that takes much longer and potentially puts a lot of unnecessary wear on the disk?

**Review by mastacontrola — COMMENTED** [review]
I might suggest:

Put the ssd wipe as a wipemode.

So do the check, if it is not frozen and has secure erase, make wipemode=ssd or something like that.

This way we don’t have an unneeded if/then/else/fi

Does that make sense?

And we really should have and end comment and maybe a debugpause for good measure.

**Comment by abulhol** [comment]
I am happy if you merge my changes.
@mastacontrola I can also make another commit with the changes you suggested, or do you want to do that then?

**Comment by Sebastian-Roth** [comment]
@mastacontrola Seems like we lost track of this.
@abulhol Would you mind adding another commit as requested?

**Comment by abulhol** [comment]
I am too busy at the moment, will make a new commit when I find the time.

**Comment by Sebastian-Roth** [comment]
@abulhol Just wondering if you'd want to get into this again?

**Comment by abulhol** [comment]
@Sebastian-Roth not really, no.

**Pull request closed without merging**
