### PR TITLE
Add space check for mounted share when capturing an image

### LINKED ISSUE #60: Add storage space check for image captures.
Currently, when capturing an image and the storage node disk is full, the output message is not very descriptive.
Current output message: `Failed to create image capture path (prepareUploadLocation)`

There was this [forum post](https://forums.fogproject.org/topic/16683/failed-to-create-image-capture-path-fog-project) that made me think that maybe there should be a check if the storage node disk is full and display a more descriptive message.

What do you think @Sebastian-Roth?
I could start work on this later in the week.

### PR DESCRIPTION
**Pull request by rluzuriaga**
Added check for the total size, used space, used space percentage, and available space for the mounted share.
Screenshot from 2023-02-21 16-22-30

Added check for the available space in the mounted share when handling the `prepareUploadLocation` failure
Screenshot from 2023-02-21 16-29-29

Resolves #60

### CODE REVIEW

**Comment by rluzuriaga** [comment]
I accidentally synced the fork after the main code commit so there is a commit for the merge.
Not sure how to remove it or if it makes any issues.

**Comment by Neustradamus** [comment]
@rluzuriaga: https://anush-venkatakrishna.medium.com/how-to-remove-undo-a-commit-from-your-pr-65e2e4e195af

**Comment by rluzuriaga** [comment]
@Neustradamus Thanks but the merge commit doesn't actually appear when I try that

**Comment by Sebastian-Roth** [comment]
@rluzuriaga said:
> I accidentally synced the fork after the main code commit so there is a commit for the merge. Not sure how to remove it or if it makes any issues.

Don't worry. When merging this we'll just do a "Squash and merge" for it to be a single commit in the end.

**Review by Sebastian-Roth — APPROVED** [review]
Looks good to me, thanks!

I just figured we have disk space alerting when saving a partition to the server fails as well - but I think this pre-flight check is great: https://github.com/FOGProject/fos/blob/master/Buildroot/board/FOG/FOS/rootfs_overlay/usr/share/fog/lib/funcs.sh#L2234 (and also line 2260)

**Comment by rluzuriaga** [comment]
@Sebastian-Roth said:
> I just figured we have disk space alerting when saving a partition to the server fails as well - but I think having the pre-flight check is great! (https://github.com/FOGProject/fos/blob/master/Buildroot/board/FOG/FOS/rootfs_overlay/usr/share/fog/lib/funcs.sh#L2234 and also line 2260)

That makes sense, I'll add it to the PR later today.

**Comment by rluzuriaga** [comment]
@Sebastian-Roth I think I understood your comment wrong. I see in [line 2234](https://github.com/FOGProject/fos/blob/master/Buildroot/board/FOG/FOS/rootfs_overlay/usr/share/fog/lib/funcs.sh#L2234) and [line 2260](https://github.com/FOGProject/fos/blob/master/Buildroot/board/FOG/FOS/rootfs_overlay/usr/share/fog/lib/funcs.sh#L2260) this code:
`Server Disk Space Available: $(df -h /images | awk '{print $4}')`

That is pretty much what I am checking for, it just displays it differently.
My implementation only displays the space. (ex. 0M, 100M, 10G)
The code that is already there in those lines prints out this:
```
Avail
0
```
It looks like this:
Screenshot from 2023-02-23 10-54-03

I can change those 2 lines to look like this instead:
Screenshot from 2023-02-23 11-09-23

---

The difference is not huge but maybe it's a good idea to standardize this. That being said I will change the wording so that it all matches.

**Review by Sebastian-Roth — APPROVED** [review]
I think it's good now. We'll see if people get to use this as a valuable information.

**Pull request merged**
