### PR TITLE
Update partclone to v0.3.20 and buildroot to v2022.02.6

### PR DESCRIPTION
**Pull request by Sebastian-Roth**

### CODE REVIEW

**Comment by Neustradamus** [comment]
@Sebastian-Roth: Currently there are new builds:
- Partclone: https://sourceforge.net/projects/partclone/files/
- Buildroot: https://buildroot.org/download.html
- Kernel: https://kernel.org/

Maybe good to update?

**Comment by Sebastian-Roth** [comment]
@Neustradamus said:
> Currently there are new builds:
> 
> * Partclone: https://sourceforge.net/projects/partclone/files/

FOG currently uses version [0.3.20](https://sourceforge.net/projects/partclone/files/0.3.20/). This has been tested a fair bit over the last three months (commit 9294193). I really don't want to blindly update to the latest 0.3.23 with not much time for testing ahead. We'll be updating to that after 1.5.10 is out.

> * Buildroot: https://buildroot.org/download.html

We use the buildroot LTS version - 2022.02.9 as of now. This version is used by the latest FOS inits (commit d4b2b0e).

> * Kernel: https://kernel.org/

Same with the kernel - LTS. Latest as of now is 5.15.95 but we updated to 5.15.93 just a few days ago (commit 6e30488). That got a bit of testing in the last days and should be fine for the release.

**Comment by Neustradamus** [comment]
@Sebastian-Roth: Thanks for your reply!

No problem ^^

Note that Linux 6.1 Kernel is LTS too:
- https://www.kernel.org/category/releases.html

**Comment by Sebastian-Roth** [comment]
@Neustradamus Yes, the 6.1 kernel source line will be made LTS at some point but it's not the case yet as far as I can tell (https://www.kernel.org/). We'll release FOG kernels based on 6.1 sooner or later... don't worry.

**Pull request merged**
